### ISSUE TITLE
How to change to US 915 Frequency..

### ISSUE THREAD

**Issue by pelvison** [wklenk/lmic-rpi-lora-gps-hat#3]
My LoraHAT seems to be working normally, but I'm not receiving the JOINED message, i believe that is because the project is set to work with europe frequency and my gateway is 915.  Normally there is config file where you can define the frequency, where do I change this in your project?. thank you, appreciate your help.

**Comment by wklenk** [comment]
To configure the LMIC communication stack to work in the 915 MHz radio band, you need to adapt a file and re-compile the stack.

The file is examples/projects.gmk:

Line 8:
```
# LMIC CONFIG
LMICCFG += -DCFG_DEBUG -DCFG_eu868 -DCFG_sx1276_radio -DDEBUG_LMIC -DDEBUG_HAL
```

 You need to replace `-DCFG_eu868` with `CFG_us915` and re-compile the examples you are using.

```
make clean
make
```
