### ISSUE TITLE
No LoRa connection 

### ISSUE THREAD

**Issue by hamelsveld** [wklenk/lmic-rpi-lora-gps-hat#9]
Hi, 

I'm using a raspberry v3 and a lorahat v 1.4 and the script does seem to run but I can't get see any data on the loranetwork. 

I'm not sure if I've done the key right in the file...
my app key is the following "86e792db42864f3b6c6d8182f26b7a19" in the file I've translated this to 

static const u1_t APPEUI[16]  = { 0x86, 0xe7, 0x92, 0xdb, 0x42, 0x86, 0x4f, 0x3b, 0x6c, 0x6d, 0x81, 0x82, 0xf2, 0x6b, 0x7a, 0x19};

Due to the LSBF statement...

I'm also not sure that my pin layout had to change in the 1,4 version... so could you please advice
 +-----+-----+---------+------+---+---Pi 3---+---+------+---------+-----+-----+
 | BCM | wPi |   Name  | Mode | V | Physical | V | Mode | Name    | wPi | BCM |
 +-----+-----+---------+------+---+----++----+---+------+---------+-----+-----+
 |     |     |    3.3v |      |   |  1 || 2  |   |      | 5v      |     |     |
 |   2 |   8 |   SDA.1 |   IN | 1 |  3 || 4  |   |      | 5v      |     |     |
 |   3 |   9 |   SCL.1 |   IN | 1 |  5 || 6  |   |      | 0v      |     |     |
 |   4 |   7 | GPIO. 7 |   IN | 0 |  7 || 8  | 1 | ALT5 | TxD     | 15  | 14  |
 |     |     |      0v |      |   |  9 || 10 | 1 | ALT5 | RxD     | 16  | 15  |
 |  17 |   0 | GPIO. 0 |   IN | 1 | 11 || 12 | 0 | IN   | GPIO. 1 | 1   | 18  |
 |  27 |   2 | GPIO. 2 |   IN | 0 | 13 || 14 |   |      | 0v      |     |     |
 |  22 |   3 | GPIO. 3 |   IN | 0 | 15 || 16 | 0 | IN   | GPIO. 4 | 4   | 23  |
 |     |     |    3.3v |      |   | 17 || 18 | 0 | IN   | GPIO. 5 | 5   | 24  |
 |  10 |  12 |    MOSI | ALT0 | 0 | 19 || 20 |   |      | 0v      |     |     |
 |   9 |  13 |    MISO | ALT0 | 0 | 21 || 22 | 1 | OUT  | GPIO. 6 | 6   | 25  |
 |  11 |  14 |    SCLK | ALT0 | 0 | 23 || 24 | 1 | OUT  | CE0     | 10  | 8   |
 |     |     |      0v |      |   | 25 || 26 | 1 | OUT  | CE1     | 11  | 7   |
 |   0 |  30 |   SDA.0 |   IN | 1 | 27 || 28 | 1 | IN   | SCL.0   | 31  | 1   |
 |   5 |  21 | GPIO.21 |   IN | 1 | 29 || 30 |   |      | 0v      |     |     |
 |   6 |  22 | GPIO.22 |   IN | 1 | 31 || 32 | 0 | IN   | GPIO.26 | 26  | 12  |
 |  13 |  23 | GPIO.23 |   IN | 0 | 33 || 34 |   |      | 0v      |     |     |
 |  19 |  24 | GPIO.24 |   IN | 0 | 35 || 36 | 0 | IN   | GPIO.27 | 27  | 16  |
 |  26 |  25 | GPIO.25 |   IN | 0 | 37 || 38 | 0 | IN   | GPIO.28 | 28  | 20  |
 |     |     |      0v |      |   | 39 || 40 | 0 | IN   | GPIO.29 | 29  | 21  |
 +-----+-----+---------+------+---+----++----+---+------+---------+-----+-----+
 | BCM | wPi |   Name  | Mode | V | Physical | V | Mode | Name    | wPi | BCM |
 +-----+-----+---------+------+---+---Pi 3---+---+------+---------+-----+-----+

Tnx in advance,

Gr Sven

**Comment by wklenk** [comment]
Hi,

you write „… I can’t get see any data on the loranetwork“.
The main question is, did the „join“ example work, as specified here: https://github.com/wklenk/lmic-rpi-lora-gps-hat/


And the next question, what kind of LoRa Gateway do you use?

If you like, send me the output of the „join“ example.

Best regards,
Wolfgang

**Comment by hamelsveld** [comment]
Hi Wolfgang,

see the following:
000000000 HAL: Initializing ...
000000002 HAL: Detected SX1276 radio module.
000000002 HAL: Set radio RST pin to 0x00
000000002 HAL: Wait until 000000003 ms
000000003 HAL: Set radio RST pin to 0x02
000000003 HAL: Wait until 000000008 ms
000000008 HAL: Receiving ...
000000014 Debug: Initializing
000000014 Debug: JOINING
000002759 Debug: EV_TXSTART
000002759 HAL: Sending ...
000007821 HAL: Receiving ...
000007821 HAL: Wait until 000007823 ms
000008868 HAL: Receiving ...
000008869 HAL: Wait until 000008870 ms

then that's it...

the output of the hello:

000000000 HAL: Initializing ...
000000004 HAL: Detected SX1276 radio module.
000000004 HAL: Set radio RST pin to 0x00
000000004 HAL: Wait until 000000005 ms
000000011 HAL: Set radio RST pin to 0x02
000000012 HAL: Wait until 000000017 ms
000000017 HAL: Receiving ...
000000032 Debug: Initializing
000000032 Debug: Hello World!

000000032 Debug: Label 'cnt = ' value 0x0
000001032 Debug: Hello World!

000001032 Debug: Label 'cnt = ' value 0x1
000002032 Debug: Hello World!

000002032 Debug: Label 'cnt = ' value 0x2
000003032 Debug: Hello World!

000003032 Debug: Label 'cnt = ' value 0x3
and so on....

Here is what we are trying to do:
we are using the dutch KPN lora network.. 

I can give you an login in that would help...


p.s. with this code I see never the blue light on the HAT go on... with an other example I did.. but also just once...

**Comment by qvs5010** [comment]
Hi hamelsvelt

have you bridged the DIO1 and DIO2 with the pi

pin 16 -------------------- DIO1
pin 18 -------------------- DIO2

**Comment by hamelsveld** [comment]
Hi,

I've just done that and with the same results ...

and no blue light

**Comment by wklenk** [comment]
Hi,

so far the output looks good.
But … do you have any evidence that the JOIN messages actually reach the KPN LoRa Network ?
Is there something like a message monitor where you see the incoming messages?

**Comment by hamelsveld** [comment]
Hi, yes they have a message monitor but I dont see any coming in :( but I also don't see the blue led blink on the HAT so that kinda indicates is not sending right?

**Comment by wklenk** [comment]
Hi,

can you be sure that you are in reach of a KPN LoRa gateway?

**Comment by hamelsveld** [comment]
Good morning, 

I'm yesterday I was at home and today in Amsterdam and on both locations it's not working. I've an other lora beacon in my bag as well and that one is working on both locations with the KPN network. 

https://www.kpn.com/zakelijk/grootzakelijk/internet-of-things/lora-netwerk.htm

is there an easy way to enable some debugging ?

**Comment by wklenk** [comment]
Hi Sven,

unfortunately, it is really hard to debug, because if the Device EUI, Application EUI and Application Key don’t match the ones defined in the KPN network, you won’t see any traffic at all. Unless KPN has some logging going on that logs nodes that aren’t actually configured.

But, if you are near Amsterdam …
Do you know „The Things Network“ ? I am part of it here in the Stuttgart region. You should have a good coverage in Amsterdam and around.
Would it be an idea to setup an account there, and try to connect to THEIR LoRa network first?

https://www.thethingsnetwork.org
https://www.thethingsnetwork.org/community/amsterdam/

If it would work there, then it also should work in the KPN network.

**Comment by hamelsveld** [comment]
Hi,

it looks like the best option. hoever last question.. How would you put these keys in the main.c?

Device EUI ->  0059AC00001818D0
Device address -> 142048D1
NwkSKey ->  4a9c2634b9f7ecf57b4e33fd14215a72
AppSKey ->. 299f9592260955d97f76f2e15b4f3693

tis is the only config I can arrange from the KPN portal

**Comment by wklenk** [comment]
Hi,

I am sorry, I have no experience with that kind of ABP (activation by personalization). 
I think in this case there is no longer the need for a JOIN operation, as the secret Network Session Key and Application Session Key are already shared between Device and the Network. So, it should be possible to send data to the network without a previous JOIN operation.

However, there is an example that demonstrates how to do ABP with the LMIC framework.
You can find it here:

https://github.com/matthijskooijman/arduino-lmic/blob/master/examples/ttn-abp/ttn-abp.ino

**Comment by hamelsveld** [comment]
if I use OTAA then I've the following config 
Device EUI
0059AC00001815D8
AppKey
86e792db42864f3b6c6d8182f26b7a19

More I can't configure .. so what and how should I put this in the main.c?

**Comment by wklenk** [comment]
Then you have a problem.
You DEFINITELY need an „Application EUI“.

**Comment by hamelsveld** [comment]
let me ask KPN what they say about that :)

**Comment by hamelsveld** [comment]
Hi, we have it running now :) tnx for your help! the app EUI did the trick...

**Comment by brady-aiello** [comment]
How do you change the frequencies? CFG_eu868 and CFG_us915 aren't defined.

**Comment by wklenk** [comment]
What do you mean with "they are not defined" ?
There is a file projects.gmk in each "examples" subdirectory.
There you find a line like:

```
# LMIC CONFIG
LMICCFG += -DCFG_DEBUG -DCFG_eu868 -DCFG_sx1276_radio -DDEBUG_LMIC -DDEBUG_HAL
```

This one defines `CFG_eu868`, but you also can replace it with `CFG_us915` .

Make sure you `make clean` in order to re-compile the LMIC library with this new compile switch set.

**Comment by brady-aiello** [comment]
Oh okay, thanks. I haven't used gmk files before. I changed it, but it is not able to join.

**Comment by bkircher67** [comment]
Hello,

unfortunately I have an equal problem. But I can see at thethingsnetwork that I have an activation (see screenshot) - but my client never gets a "JOINED" event ...
<img width="1063" alt="ttn_activation" src="https://user-images.githubusercontent.com/586166/43341873-18f8e65a-91e1-11e8-9757-0ff27b113e82.png">

Here's my client's logfile (with the periodic-example)

```
pi@raspberrypi3:~/Lora/lmic-rpi-lora-gps-hat/examples/periodic $ sudo ./build/periodic.out 
000000000 HAL: Initializing ...
000000002 HAL: Detected SX1276 radio module.
000000002 HAL: Set radio RST pin to 0x00
000000002 HAL: Wait until 000000003 ms
000000004 HAL: Set radio RST pin to 0x02
000000004 HAL: Wait until 000000009 ms
000000009 HAL: Receiving ...
000000019 Debug: Initializing
000000020 Debug: JOINING
000007903 Debug: EV_TXSTART
000007904 HAL: Sending ...
000012965 HAL: Receiving ...
000012965 HAL: Wait until 000012967 ms
000014013 HAL: Receiving ...
000014013 HAL: Wait until 000014015 ms
000074272 Debug: EV_TXSTART
000074273 HAL: Sending ...
000079334 HAL: Receiving ...
000079334 HAL: Wait until 000079336 ms
000080382 HAL: Receiving ...
000080382 HAL: Wait until 000080384 ms
000150681 Debug: EV_TXSTART
000150682 HAL: Sending ...
000155796 HAL: Receiving ...
 ```

**Comment by wklenk** [comment]
Let me ask you some questions:

Q1: You are currently trying out example "periodic". Did you try out example "join" before, and did that work, meaning, did it output "JOINED" after some seconds? 

Q2: What kind of LoRa Gateway are you using? Multi-channel with full functionality, or some experimental single-channel gateway?

**Comment by bkircher67** [comment]
Hello,

Thank you for your quick reply.

add Q1: No, I didn't try out join. I did it now. It works (but it took several minutes to JOIN):

```
pi@raspberrypi3:~/Lora/lmic-rpi-lora-gps-hat/examples/join $ sudo ./build/join.out 
000000000 HAL: Initializing ...
000000004 HAL: Detected SX1276 radio module.
000000004 HAL: Set radio RST pin to 0x00
000000004 HAL: Wait until 000000005 ms
000000005 HAL: Set radio RST pin to 0x02
000000006 HAL: Wait until 000000011 ms
000000013 HAL: Receiving ...
000000034 Debug: Initializing
000000034 Debug: JOINING
000006424 Debug: EV_TXSTART
...
000407658 Debug: EV_TXSTART
000407659 HAL: Sending ...
000412869 HAL: Receiving ...
000412869 HAL: Wait until 000412871 ms
000413114 Debug: JOINED
```

add Q2) I'm using a public TTN network somewhere at a University nearby. But I will try the Dragino LG01-P today.

I also see that now that periodic is working too - after 15min of waiting. In my tests with the TTN Uno It also took quite a long time to get a working connection, but I always received some information like 

```
Join not accepted: denied
Check your coverage, keys and backend status.
```
OR
```
Sending: mac join otaa 
Response is not OK: no_free_ch
Send join command failed
``` 


KR Bernd

**Comment by wklenk** [comment]
Okay, I see ...
Most probably the LoRa gateway you are connecting to only supports a single frequency. The LMIC stack chooses the frequency to join by random, so it may take some time until it hits the (single) join frequency of this gateway.

**Comment by johnnyenglish1970** [comment]
Hi Wolfgang,
I'm also having this issue - I never get the 'Joined' response as exactly the above examples.
I'm running a RPI v3 with the lora hat v1.4 - using a Dragino LG01-P Gateway (on 868.1Mhz).
I wonder if it is a channel issue as the LG01-P is single channel?  I was thinking about trying to change the setting for number of channels in the lmic.c file to '1' - or somehow set all the channels to the same 868.1 frequency. Do you think that might work?
Seems like a lot of us are having this issue!
Thanks,

**Comment by wklenk** [comment]
Yes, it has to do with the fact that the LMIC stack selects the join frequency randomly. The LG01-S is an open source single channel LoRa Gateway. So it can take some time until you hit the right "single channel" frequency. It is also not clear if the LG01 handles join-accept messages in the right way. My recommendation is to try it out with a fully functional LoRa Gateway.
